### ISSUE TITLE
META: Define Developer Site design process

### ISSUE THREAD

**Issue by cassiemc** [adobe/developer.adobe.com#20]
It'd be a good idea to lay out the design process so the team knows where we're at and can contribute accordingly. For each of these tasks I'll file more granular tickets if necessary. I'm sure the end process won't be this tidy or linear but this should give an overarching idea of how things might go in an ideal world. Some of this will include overlap with Console design work which won't be documented here.

### Define, Discover, Research

- [ ] Define design goals for this project & success metrics, incl. design principles & resources (in progress)
- [ ] Define design approval process (ie. what's listed here + RACI (Responsible, Accountable, Consulted, Informed): who inputs, who signs off + deadlines)
- [x] Stakeholder user research (#38) & synthesis (#41)
- [ ] Competitor research/synthesis (in progress) (#154)
- [ ] Write & prioritize user journeys, use cases. This will inform user test criteria. (in progress) #153 
- [ ] Validation of the above priorities, if needed

### UX Design & Testing
- [x] Create maintainable IA doc (#5)
- [ ] Wireframes (homepage, product landings, etc.) <- this list will grow, no doubt
- [ ] Wireframe and prototype Documentation (early days, but in progress)
- [ ] Map the above user journeys against working IA docs/wireframes
- [ ] Prototype
- [ ] User test

### Implementation
- [ ] UI design
- [ ] Implementation
- [ ] Testing/QA
- [ ] Adjustments

@cmgeorge16 @simonwex This is based a bit on Razvan's fab process work via Atlas. What have I missed or needs fleshing out to get us on the same page?

**Comment by cassiemc** [comment]
This is being better tracked now in a google sheet. See https://docs.google.com/spreadsheets/d/1pOg2NGTqvUiNgLdDwtK-F93rW62PdDkUWTjDGyMyp2I/edit?usp=sharing

Details will change, screenshot for preview only. [CLICK THE LINK!](https://docs.google.com/spreadsheets/d/1pOg2NGTqvUiNgLdDwtK-F93rW62PdDkUWTjDGyMyp2I/edit?usp=sharing) :)
![screen shot 2019-03-01 at 1 47 25 pm](https://user-images.githubusercontent.com/1186326/53659079-99e83080-3c28-11e9-8d27-7c26c1d8dc40.png)
